ASSIGNMENT 4


Question 1: Write a program to create a NumPy 1D-array with 5 elements and perform basic operations.



a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2


In [1]:
import numpy as np
x=[1,2,3,4,5]
arr=np.array(x)
#1)-(a)
arr_sum=arr+2
print(arr_sum)
#1)-(b)
arr_multiply=arr*3
print(arr_multiply)
#1)-(c)
arr_div=arr/2
print(arr_div)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Question 2: Questions on Basic NumPy Array.



a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [2]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent = np.bincount(x).argmax()  
indices = np.where(x == most_frequent)[0]  
print(f"Most frequent value: {most_frequent}, Indices: {indices}")

Most frequent value: 1, Indices: [0 5 7 8 9]


b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent = np.bincount(y).argmax()  
indices = np.where(y == most_frequent)[0]  
print(f"Most frequent value: {most_frequent}, Indices: {indices}")

Most frequent value: 1, Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element_1_2 = arr[0][1]
print("Element at (1st row, 2nd column):", element_1_2)

Element at (1st row, 2nd column): 20


b) Access 3rd row, 1st column

In [5]:
element_3_1 = arr[2][0]
print("Element at (3rd row, 1st column):", element_3_1)

Element at (3rd row, 1st column): 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [6]:
Snehil=np.linspace(10,100,25)
print(Snehil)
print("\nDimensions:",Snehil.shape)
print("\nTotal elements:",Snehil.size)
print("\nData Type of each element:",Snehil.dtype)
print("\nTotal Number of bytes consumed:",Snehil.itemsize*Snehil.size)
print("\nTranspose:\n",Snehil.reshape(25))
Snehil.T
print("\nYes,we can do the Transpose of this array using T attribute")

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: (25,)

Total elements: 25

Data Type of each element: float64

Total Number of bytes consumed: 200

Transpose:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Yes,we can do the Transpose of this array using T attribute


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [8]:
UCS420_Snehil = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

print("Mean:", np.mean(UCS420_Snehil))
print("\nMedian:", np.median(UCS420_Snehil))
print("\nMax:", np.max(UCS420_Snehil))
print("\nMin:", np.min(UCS420_Snehil))
print("\nUnique elements:", np.unique(UCS420_Snehil))
reshaped_UCS420_Snehil = UCS420_Snehil.reshape(4, 3)
print("\nReshaped array (4 rows * 3 columns):\n", reshaped_UCS420_Snehil)
resized_UCS420_Snehil = np.resize(UCS420_Snehil, (2, 3))
print("\nResized array (2 rows * 3 columns):\n", resized_UCS420_Snehil)

Mean: 43.333333333333336

Median: 37.5

Max: 90

Min: 10

Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 rows * 3 columns):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 rows * 3 columns):
 [[10 20 30]
 [40 50 60]]
